In [1]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving credit card.csv to credit card.csv
User uploaded file "credit card.csv" with length 2905728 bytes


In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ModuleNotFoundError: ignored

In [3]:
df = pd.read_csv('credit card.csv')

In [4]:
df

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE   AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1  24.0      2      2     -1   
1          2   120000.0    2          2         2  26.0     -1      2      0   
2          3    90000.0    2          2         2   NaN      0      0      0   
3          4    50000.0    2          2         1   NaN      0      0      0   
4          5    50000.0    1          2         1  57.0     -1      0     -1   
...      ...        ...  ...        ...       ...   ...    ...    ...    ...   
29995  29996   220000.0    1          3         1  39.0      0      0      0   
29996  29997   150000.0    1          3         2  43.0     -1     -1     -1   
29997  29998    30000.0    1          2         2  37.0      4      3      2   
29998  29999    80000.0    1          3         1  41.0      1     -1      0   
29999  30000    50000.0    1          2         1  46.0      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...        0.0        0.0        0.0       0.0     689.0   
1          0  ...     3272.0     3455.0     3261.0       0.0    1000.0   
2          0  ...    14331.0    14948.0    15549.0    1518.0    1500.0   
3          0  ...    28314.0    28959.0    29547.0    2000.0    2018.0   
4          0  ...    20940.0    19146.0    19131.0    2000.0   36681.0   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...    88004.0    31237.0    15980.0    8500.0   20000.0   
29996     -1  ...     8979.0     5190.0        0.0    1837.0    3526.0   
29997     -1  ...    20878.0    20582.0    19357.0       0.0       0.0   
29998      0  ...    52774.0    11855.0    48944.0   85900.0    3409.0   
29999      0  ...    36535.0    32428.0    15313.0    2078.0    1800.0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0           0.0       0.0       0.0       0.0                           1  
1        1000.0    1000.0       0.0    2000.0                           1  
2        1000.0    1000.0    1000.0    5000.0                           0  
3        1200.0    1100.0    1069.0    1000.0                           0  
4       10000.0    9000.0     689.0     679.0                           0  
...         ...       ...       ...       ...                         ...  
29995    5003.0    3047.0    5000.0    1000.0                           0  
29996    8998.0     129.0       0.0       0.0                           0  
29997   22000.0    4200.0    2000.0    3100.0                           1  
29998    1178.0    1926.0   52964.0    1804.0                           1  
29999    1430.0    1000.0    1000.0    1000.0                           1  

[30000 rows x 25 columns]

In [5]:
df.shape

(30000, 25)

In [6]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           2
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [7]:
fill= df['AGE'].median()

In [8]:
df.AGE = df.AGE.fillna(fill)

In [9]:
df.AGE

0        24.0
1        26.0
2        34.0
3        34.0
4        57.0
         ... 
29995    39.0
29996    43.0
29997    37.0
29998    41.0
29999    46.0
Name: AGE, Length: 30000, dtype: float64

In [10]:
X = df.drop(['default.payment.next.month'],axis=1)

In [11]:
X

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE   AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1  24.0      2      2     -1   
1          2   120000.0    2          2         2  26.0     -1      2      0   
2          3    90000.0    2          2         2  34.0      0      0      0   
3          4    50000.0    2          2         1  34.0      0      0      0   
4          5    50000.0    1          2         1  57.0     -1      0     -1   
...      ...        ...  ...        ...       ...   ...    ...    ...    ...   
29995  29996   220000.0    1          3         1  39.0      0      0      0   
29996  29997   150000.0    1          3         2  43.0     -1     -1     -1   
29997  29998    30000.0    1          2         2  37.0      4      3      2   
29998  29999    80000.0    1          3         1  41.0      1     -1      0   
29999  30000    50000.0    1          2         1  46.0      0      0      0   

       PAY_4  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0         -1  ...      689.0        0.0        0.0        0.0       0.0   
1          0  ...     2682.0     3272.0     3455.0     3261.0       0.0   
2          0  ...    13559.0    14331.0    14948.0    15549.0    1518.0   
3          0  ...    49291.0    28314.0    28959.0    29547.0    2000.0   
4          0  ...    35835.0    20940.0    19146.0    19131.0    2000.0   
...      ...  ...        ...        ...        ...        ...       ...   
29995      0  ...   208365.0    88004.0    31237.0    15980.0    8500.0   
29996     -1  ...     3502.0     8979.0     5190.0        0.0    1837.0   
29997     -1  ...     2758.0    20878.0    20582.0    19357.0       0.0   
29998      0  ...    76304.0    52774.0    11855.0    48944.0   85900.0   
29999      0  ...    49764.0    36535.0    32428.0    15313.0    2078.0   

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         689.0       0.0       0.0       0.0       0.0  
1        1000.0    1000.0    1000.0       0.0    2000.0  
2        1500.0    1000.0    1000.0    1000.0    5000.0  
3        2018.0    1200.0    1100.0    1069.0    1000.0  
4       36681.0   10000.0    9000.0     689.0     679.0  
...         ...       ...       ...       ...       ...  
29995   20000.0    5003.0    3047.0    5000.0    1000.0  
29996    3526.0    8998.0     129.0       0.0       0.0  
29997       0.0   22000.0    4200.0    2000.0    3100.0  
29998    3409.0    1178.0    1926.0   52964.0    1804.0  
29999    1800.0    1430.0    1000.0    1000.0    1000.0  

[30000 rows x 24 columns]

In [12]:
y= df['default.payment.next.month']

In [13]:
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default.payment.next.month, Length: 30000, dtype: int64

In [14]:
#Dataset splitting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.30,random_state=1)

In [18]:
#Train Model 
import seaborn
from sklearn.svm import SVC
r=SVC(gamma='auto')

In [22]:
r.fit(X_train, y_train)

SVC(gamma='auto')

In [23]:
#predict
pred2= r.predict(X_test)

In [24]:
r.score(X_test,y_test)

0.7777777777777778

In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
accuracy_score(y_test,pred2)

0.7777777777777778

In [26]:
confusion_matrix(y_test,pred2)

array([[7000,    0],
       [2000,    0]])

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=50)
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [32]:
pred1 = rf.predict(X_test)
rf.score(X_test,y_test)

0.8124444444444444

In [33]:
accuracy_score(y_test,pred1)

0.8124444444444444

In [34]:
confusion_matrix(y_test,pred1)

array([[6616,  384],
       [1304,  696]])

In [35]:
classification_report(y_test,pred1)

print(classification_report(y_test,pred1))



              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7000
           1       0.64      0.35      0.45      2000

    accuracy                           0.81      9000
   macro avg       0.74      0.65      0.67      9000
weighted avg       0.79      0.81      0.79      9000



In [36]:
from sklearn.tree import DecisionTreeClassifier
d = DecisionTreeClassifier()
d.fit(X_train, y_train)

DecisionTreeClassifier()

In [37]:
pred=d.predict(X_test)
d.score(X_test,y_test)

0.7223333333333334

In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report

In [39]:
accuracy_score(y_test,pred)

0.7223333333333334

In [40]:
confusion_matrix(y_test,pred)


array([[5653, 1347],
       [1152,  848]])

In [41]:
classification_report(y_test,pred)

print(classification_report(y_test,pred))


              precision    recall  f1-score   support

           0       0.83      0.81      0.82      7000
           1       0.39      0.42      0.40      2000

    accuracy                           0.72      9000
   macro avg       0.61      0.62      0.61      9000
weighted avg       0.73      0.72      0.73      9000



In [42]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

In [43]:
#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
gnb.predict(X_test)

array([1, 1, 0, ..., 1, 1, 1])

In [44]:
gnb.score(X_test,y_test)

0.37744444444444447

In [45]:
from sklearn.naive_bayes import BernoulliNB

#Create a Gaussian Classifier
bnb = BernoulliNB()

In [46]:
#Train the model using the training sets
bnb.fit(X_train, y_train)

#Predict the response for test dataset
bnb.predict(X_test)

array([0, 1, 0, ..., 0, 0, 0])

In [47]:
bnb.score(X_test,y_test)

0.771

In [50]:
#Train the model using the training sets
#mnb.fit(X_train, y_train)

#Predict the response for test dataset
#mnb.predict(X_test)